### ISSUE TITLE
Error with require 

### ISSUE THREAD

**Issue by ambarja** [gee-community/eetasks#22]
Hello, I recently used this plugin for vscode, but the require function is not defined or has an error.
Is it possible to call the require function?
Some users have multiple functions of various processes stored in various js codes that when using only call with require, this if you work directly with the Code Editor has no problems.
![image](https://github.com/user-attachments/assets/f241d836-714a-42c4-8388-c65d0acb161f)
Here are some references
References: 
- https://github.com/awesome-spectral-indices/spectral
- https://github.com/ambarja/ee-cptcity

**Comment by lopezvoliver** [comment]
Hi, `require` is not yet implemented in the eetasks extension, but it's definitely a feature that I have in mind for developing. I'll keep this issue open as a reminder.

**Comment by lopezvoliver** [comment]
@ambarja I added `request` as a new feature to the GEE script runner (see #23). To use this, there are two pre-requisites:

1. You must have `git` installed
2. You must generate a git cookie for Earth Engine by visiting and following the instructions from:
 
https://earthengine.googlesource.com/new-password

I just published the new version (v0.4.0) to the vscode Marketplace. Please update it and let me know if it works in your example.

**Comment by ambarja** [comment]
Nice job! @lopezvoliver.
Thank you for consider my "issue" 
Now it's possible to use multiple modules developed in Js 
![image](https://github.com/user-attachments/assets/0dcc0777-8e7b-45f6-95ae-d54684560f90)
